using System.Diagnostics;
using System.Text.Json;
using Ardalis.Result;
using MediatR;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;
using Vetolib.AI.Application.Domain;
using Vetolib.AI.Contracts;
using Vetolib.AI.Infrastructure;

namespace Vetolib.AI.Application.Commands.TriageSymptoms;

internal class TriageSymptomsHandler : IRequestHandler<TriageSymptomsCommand, Result<TriageSuggestionDto>>
{
    internal const string Disclaimer =
        "This suggestion is generated by artificial intelligence for informational purposes only. " +
        "It does not constitute a veterinary diagnosis. " +
        "Only a licensed veterinarian can diagnose and prescribe treatment. " +
        "If in doubt about the severity, contact your veterinarian immediately.";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    private const string SystemPrompt = """
        You are a veterinary triage assistant. Your role is to analyze pet symptoms and suggest
        an urgency level, estimated consultation duration, and recommended specialty.

        IMPORTANT RULES:
        - Never recommend specific medications or treatments.
        - Never provide a diagnosis — only urgency classification.
        - Classify severity as one of exactly three values: Emergency, Normal, Routine.
        - Emergency: life-threatening symptoms requiring immediate attention (toxin ingestion, severe trauma,
          breathing difficulty, collapse, uncontrolled bleeding, neurological signs).
        - Normal: symptoms requiring prompt veterinary attention within 24–48 hours.
        - Routine: non-urgent symptoms that can be addressed at the next available appointment.

        Respond ONLY with a valid JSON object matching this exact schema:
        {
          "severity": "Emergency" | "Normal" | "Routine",
          "estimatedDurationMinutes": <integer between 15 and 120>,
          "recommendedSpecialty": <string, e.g. "general practitioner", "emergency", "dermatology", "ophthalmology", "orthopedics", "internal medicine">,
          "reasoning": <string, brief clinical reasoning in English, max 200 words>,
          "confidence": <float between 0.0 and 1.0>
        }

        Do not include any text outside the JSON object.
        """;

    private readonly AIDbContext _context;
    private readonly IChatClient? _chatClient;
    private readonly ILogger<TriageSymptomsHandler> _logger;

    public TriageSymptomsHandler(
        AIDbContext context,
        ILogger<TriageSymptomsHandler> logger,
        IChatClient? chatClient = null)
    {
        _context = context;
        _logger = logger;
        _chatClient = chatClient;
    }

    public async Task<Result<TriageSuggestionDto>> Handle(
        TriageSymptomsCommand cmd,
        CancellationToken ct)
    {
        if (_chatClient is null)
        {
            _logger.LogWarning("AI triage requested but IChatClient is not configured.");
            return Result<TriageSuggestionDto>.Error("AI_SERVICE_UNAVAILABLE");
        }

        var userMessage = BuildUserMessage(cmd);

        var sw = Stopwatch.StartNew();
        ChatResponse completion;

        try
        {
            var messages = new List<ChatMessage>
            {
                new(ChatRole.System, SystemPrompt),
                new(ChatRole.User, userMessage)
            };

            var options = new ChatOptions
            {
                Temperature = 0.1f,
                ResponseFormat = ChatResponseFormat.Json
            };

            completion = await _chatClient.GetResponseAsync(messages, options, ct);
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            _logger.LogError(ex, "AI service call failed for triage request.");
            return Result<TriageSuggestionDto>.Error("AI_SERVICE_UNAVAILABLE");
        }

        sw.Stop();

        var rawResponse = completion.Text ?? string.Empty;
        TriageAiResponse? parsed;

        try
        {
            parsed = JsonSerializer.Deserialize<TriageAiResponse>(rawResponse, JsonOptions);
        }
        catch (JsonException ex)
        {
            _logger.LogError(ex, "Failed to parse AI response: {Response}", rawResponse);
            return Result<TriageSuggestionDto>.Error("AI_RESPONSE_INVALID");
        }

        if (parsed is null || !IsValidSeverity(parsed.Severity))
        {
            _logger.LogError("AI response missing or invalid severity: {Response}", rawResponse);
            return Result<TriageSuggestionDto>.Error("AI_RESPONSE_INVALID");
        }

        var severity = Enum.Parse<AISeverity>(parsed.Severity, ignoreCase: true);
        var modelUsed = GetModelName(completion);
        var promptTokens = (int)(completion.Usage?.InputTokenCount ?? 0);
        var completionTokens = (int)(completion.Usage?.OutputTokenCount ?? 0);

        var triageResultResult = TriageResult.Create(
            clinicId: cmd.ClinicId,
            symptoms: cmd.Symptoms,
            species: cmd.Species,
            breed: cmd.Breed,
            ageMonths: cmd.AgeMonths,
            weightKg: cmd.WeightKg,
            suggestedSeverity: severity,
            estimatedDurationMinutes: parsed.EstimatedDurationMinutes,
            recommendedSpecialty: parsed.RecommendedSpecialty ?? string.Empty,
            reasoning: parsed.Reasoning ?? string.Empty,
            confidence: parsed.Confidence,
            modelUsed: modelUsed,
            promptTokens: promptTokens,
            completionTokens: completionTokens,
            latencyMs: sw.ElapsedMilliseconds,
            createdBy: cmd.CreatedBy);

        if (!triageResultResult.IsSuccess)
            return Result<TriageSuggestionDto>.Error("AI_RESPONSE_INVALID");

        _context.TriageResults.Add(triageResultResult.Value);

        try
        {
            await _context.SaveChangesAsync(ct);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to persist triage result.");
            // Return the result anyway — persistence failure should not block the user
        }

        var dto = new TriageSuggestionDto(
            TriageId: triageResultResult.Value.Id,
            Severity: severity,
            EstimatedDurationMinutes: parsed.EstimatedDurationMinutes,
            RecommendedSpecialty: parsed.RecommendedSpecialty ?? string.Empty,
            Reasoning: parsed.Reasoning ?? string.Empty,
            Disclaimer: Disclaimer,
            Confidence: parsed.Confidence);

        return Result<TriageSuggestionDto>.Success(dto);
    }

    private static string BuildUserMessage(TriageSymptomsCommand cmd)
    {
        var parts = new List<string>
        {
            $"Species: {cmd.Species}",
            $"Symptoms: {cmd.Symptoms}"
        };

        if (!string.IsNullOrWhiteSpace(cmd.Breed))
            parts.Add($"Breed: {cmd.Breed}");

        if (cmd.AgeMonths.HasValue)
            parts.Add($"Age: {cmd.AgeMonths.Value} months");

        if (cmd.WeightKg.HasValue)
            parts.Add($"Weight: {cmd.WeightKg.Value} kg");

        return string.Join("\n", parts);
    }

    private static bool IsValidSeverity(string? severity) =>
        severity is not null &&
        (severity.Equals("Emergency", StringComparison.OrdinalIgnoreCase) ||
         severity.Equals("Normal", StringComparison.OrdinalIgnoreCase) ||
         severity.Equals("Routine", StringComparison.OrdinalIgnoreCase));

    private static string GetModelName(Microsoft.Extensions.AI.ChatResponse completion)
    {
        // Try to extract model name from the completion metadata
        if (completion.ModelId is not null)
            return completion.ModelId;

        if (completion.AdditionalProperties?.TryGetValue("model", out var model) == true && model is string modelStr)
            return modelStr;

        return "unknown";
    }

    private sealed record TriageAiResponse(
        string Severity,
        int EstimatedDurationMinutes,
        string? RecommendedSpecialty,
        string? Reasoning,
        double Confidence);
}
