using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Vetolib.Billing.Contracts;

namespace Vetolib.Billing.Application.Queries.GenerateInvoicePdf;

/// <summary>
/// Factur-X PDF generator for French clinics.
/// Produces a PDF/A-3 with an embedded CII XML attachment (factur-x.xml).
/// The visual PDF uses the same layout as <see cref="StandardPdfGenerator"/>,
/// plus a notice that the invoice is Factur-X compliant.
/// </summary>
internal class FacturXPdfGenerator : IInvoicePdfGenerator
{
    /// <summary>
    /// Generates a Factur-X PDF: visual PDF with embedded CII XML (factur-x.xml).
    /// </summary>
    public byte[] Generate(InvoiceDto invoice, string clinicName, string taxRegistrationNumber)
    {
        // 1. Generate CII XML
        var xmlBytes = FacturXXmlGenerator.Generate(invoice, clinicName, taxRegistrationNumber);

        // 2. Generate visual PDF via QuestPDF
        QuestPDF.Settings.License = LicenseType.Community;

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Element(c => ComposeHeader(c, clinicName, taxRegistrationNumber, invoice.CountryCode));
                page.Content().Column(content =>
                {
                    content.Item().Element(c => ComposeContent(c, invoice));
                    content.Item().Element(c => ComposeLegalMentions(c, invoice));
                    content.Item().Element(ComposeFacturXNotice);
                });
                page.Footer().Column(footer =>
                {
                    footer.Item().AlignCenter().Text(x =>
                    {
                        x.Span("Thank you for trusting us with your pet!").Italic();
                    });
                    footer.Item().PaddingTop(4).AlignCenter().Text(x =>
                    {
                        x.Span("Generated by Vetara ~ vetara.com").FontSize(8).FontColor(Colors.Grey.Medium);
                    });
                });
            });
        });

        var pdfBytes = document.GeneratePdf();

        // 3. Embed XML into PDF as attachment
        return EmbedXmlAttachment(pdfBytes, xmlBytes);
    }

    /// <summary>
    /// Embeds the factur-x.xml into the PDF as a file attachment.
    /// Uses a simple PDF append approach: adds an embedded file stream and catalog entry.
    /// </summary>
    internal static byte[] EmbedXmlAttachment(byte[] pdfBytes, byte[] xmlBytes)
    {
        // Use a straightforward approach: append the XML data as a PDF embedded file.
        // For production-grade PDF/A-3, a dedicated library like iText or PDFSharp would be ideal.
        // Here we use a minimal but functional approach to embed the XML as Associated File.
        using var outputStream = new MemoryStream();
        using var writer = new BinaryWriter(outputStream);

        // Write original PDF (minus the final %%EOF line so we can append objects)
        var pdfString = System.Text.Encoding.Latin1.GetString(pdfBytes);
        var eofIndex = pdfString.LastIndexOf("%%EOF", StringComparison.Ordinal);

        // Find the last xref offset line before %%EOF
        var startxrefIndex = pdfString.LastIndexOf("startxref", StringComparison.Ordinal);
        var existingXrefOffset = 0L;
        if (startxrefIndex > 0)
        {
            var afterStartxref = pdfString.Substring(startxrefIndex + "startxref".Length).Trim();
            var lines = afterStartxref.Split('\n');
            if (lines.Length > 0)
                long.TryParse(lines[0].Trim(), out existingXrefOffset);
        }

        // Write the original PDF content up to %%EOF
        var originalBytes = eofIndex > 0 ? pdfBytes[..eofIndex] : pdfBytes;
        writer.Write(originalBytes);

        // Find the next available object number by scanning for "N 0 obj" patterns
        var nextObjNum = 1;
        for (var i = 0; i < pdfString.Length - 5; i++)
        {
            if (pdfString[i] >= '0' && pdfString[i] <= '9')
            {
                var j = i;
                while (j < pdfString.Length && pdfString[j] >= '0' && pdfString[j] <= '9') j++;
                if (j + 5 < pdfString.Length && pdfString.Substring(j, 6) == " 0 obj")
                {
                    if (int.TryParse(pdfString[i..j], out var objNum) && objNum >= nextObjNum)
                        nextObjNum = objNum + 1;
                }
            }
        }

        // Object: Embedded file stream containing the XML
        var streamObjNum = nextObjNum;
        var streamObjOffset = outputStream.Position;
        var streamObj = $"{streamObjNum} 0 obj\n" +
                       $"<< /Type /EmbeddedFile /Subtype /text#2Fxml /Length {xmlBytes.Length} >>\n" +
                       "stream\n";
        writer.Write(System.Text.Encoding.Latin1.GetBytes(streamObj));
        writer.Write(xmlBytes);
        writer.Write(System.Text.Encoding.Latin1.GetBytes("\nendstream\nendobj\n"));

        // Object: File specification
        var fileSpecObjNum = streamObjNum + 1;
        var fileSpecObjOffset = outputStream.Position;
        var fileSpecObj = $"{fileSpecObjNum} 0 obj\n" +
                         $"<< /Type /Filespec /F (factur-x.xml) /UF (factur-x.xml) " +
                         $"/EF << /F {streamObjNum} 0 R /UF {streamObjNum} 0 R >> " +
                         $"/AFRelationship /Data /Desc (Factur-X EN16931 CII XML) >>\n" +
                         "endobj\n";
        writer.Write(System.Text.Encoding.Latin1.GetBytes(fileSpecObj));

        // Write cross-reference table for the new objects
        var xrefOffset = outputStream.Position;
        var xref = "xref\n" +
                  $"{streamObjNum} 2\n" +
                  $"{streamObjOffset:D10} 00000 n \n" +
                  $"{fileSpecObjOffset:D10} 00000 n \n";
        writer.Write(System.Text.Encoding.Latin1.GetBytes(xref));

        // Trailer
        var trailer = "trailer\n" +
                     $"<< /Size {fileSpecObjNum + 1} /Prev {existingXrefOffset} >>\n" +
                     "startxref\n" +
                     $"{xrefOffset}\n" +
                     "%%EOF\n";
        writer.Write(System.Text.Encoding.Latin1.GetBytes(trailer));

        writer.Flush();
        return outputStream.ToArray();
    }

    private static void ComposeFacturXNotice(IContainer container)
    {
        container.PaddingTop(12)
            .Background(Colors.Blue.Lighten5)
            .Padding(8)
            .Column(col =>
            {
                col.Item().Text("Factur-X EN16931")
                    .Bold().FontSize(9).FontColor(Colors.Blue.Darken2);
                col.Item().Text("This invoice contains an embedded XML file (factur-x.xml) conforming to the EN16931 standard for electronic invoicing.")
                    .FontSize(8).FontColor(Colors.Blue.Darken1);
            });
    }

    private static void ComposeHeader(IContainer container, string clinicName, string taxRegistrationNumber, string countryCode)
    {
        var locationLabel = countryCode.ToUpperInvariant() switch
        {
            "FR" => "France",
            "DE" => "Germany",
            "BE" => "Belgium",
            _ => countryCode
        };

        container
            .BorderBottom(1)
            .BorderColor(Colors.Grey.Medium)
            .PaddingBottom(10)
            .Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(clinicName.ToUpperInvariant())
                        .Bold().FontSize(16);
                    col.Item().Text(locationLabel).FontSize(11);
                    if (!string.IsNullOrWhiteSpace(taxRegistrationNumber))
                        col.Item().Text($"VAT: {taxRegistrationNumber}").FontColor(Colors.Grey.Darken1);
                });
            });
    }

    private static void ComposeLegalMentions(IContainer container, InvoiceDto invoice)
    {
        container.PaddingTop(16).Column(col =>
        {
            if (!string.IsNullOrWhiteSpace(invoice.SellerSiren))
                col.Item().Text($"SIREN: {invoice.SellerSiren}").FontSize(8).FontColor(Colors.Grey.Darken1);
            if (!string.IsNullOrWhiteSpace(invoice.SellerVatNumber))
                col.Item().Text($"VAT: {invoice.SellerVatNumber}").FontSize(8).FontColor(Colors.Grey.Darken1);

            if (!string.IsNullOrWhiteSpace(invoice.BuyerName))
                col.Item().PaddingTop(4).Text($"Client: {invoice.BuyerName}").FontSize(9);
            if (!string.IsNullOrWhiteSpace(invoice.BuyerAddress))
                col.Item().Text(invoice.BuyerAddress).FontSize(8).FontColor(Colors.Grey.Darken1);
            if (!string.IsNullOrWhiteSpace(invoice.BuyerSiren))
                col.Item().Text($"SIREN: {invoice.BuyerSiren}").FontSize(8).FontColor(Colors.Grey.Darken1);
            if (!string.IsNullOrWhiteSpace(invoice.BuyerVatNumber))
                col.Item().Text($"VAT: {invoice.BuyerVatNumber}").FontSize(8).FontColor(Colors.Grey.Darken1);

            if (!string.IsNullOrWhiteSpace(invoice.PaymentTerms))
                col.Item().PaddingTop(4).Text($"Payment terms: {invoice.PaymentTerms}").FontSize(8);

            if (!string.IsNullOrWhiteSpace(invoice.PurchaseOrderReference))
                col.Item().Text($"PO Ref: {invoice.PurchaseOrderReference}").FontSize(8);

            var typeLabel = invoice.InvoiceTypeCode switch
            {
                "381" => "CREDIT NOTE",
                _ => "INVOICE"
            };
            col.Item().PaddingTop(4).Text($"Document type: {typeLabel} ({invoice.InvoiceTypeCode})")
                .FontSize(8).FontColor(Colors.Grey.Darken1);
        });
    }

    private static void ComposeContent(IContainer container, InvoiceDto invoice)
    {
        container.PaddingTop(20).Column(col =>
        {
            col.Item().Table(table =>
            {
                table.ColumnsDefinition(c =>
                {
                    c.RelativeColumn();
                    c.RelativeColumn();
                });

                table.Cell().Column(1).Text($"INVOICE #{invoice.InvoiceNumber}").Bold().FontSize(13);
                table.Cell().Column(2).AlignRight().Text($"Date: {invoice.CreatedAt:dd/MM/yyyy}");

                var statusLabel = invoice.Status switch
                {
                    InvoiceStatus.Paid => invoice.DueDate.HasValue
                        ? $"PAID (due {invoice.DueDate.Value:dd/MM/yyyy})"
                        : "PAID",
                    InvoiceStatus.Sent => invoice.DueDate.HasValue
                        ? $"SENT — Due: {invoice.DueDate.Value:dd/MM/yyyy}"
                        : "SENT",
                    _ => invoice.Status.ToString().ToUpperInvariant()
                };

                table.Cell().ColumnSpan(2).PaddingTop(4).Text($"Status: {statusLabel}");
            });

            col.Item().PaddingTop(16).PaddingBottom(8)
                .BorderBottom(1).BorderColor(Colors.Grey.Lighten2)
                .Height(1);

            col.Item().PaddingTop(8).Table(table =>
            {
                table.ColumnsDefinition(c =>
                {
                    c.ConstantColumn(30);
                    c.RelativeColumn();
                    c.ConstantColumn(100);
                    c.ConstantColumn(70);
                    c.ConstantColumn(100);
                });

                static IContainer HeaderCell(IContainer c) =>
                    c.DefaultTextStyle(x => x.Bold())
                     .Background(Colors.Grey.Lighten3)
                     .PaddingVertical(5)
                     .PaddingHorizontal(4);

                table.Header(header =>
                {
                    header.Cell().Element(HeaderCell).Text("#");
                    header.Cell().Element(HeaderCell).Text("Description");
                    header.Cell().Element(HeaderCell).AlignRight().Text($"Unit ({invoice.CurrencyCode} excl.)");
                    header.Cell().Element(HeaderCell).AlignRight().Text("Tax %");
                    header.Cell().Element(HeaderCell).AlignRight().Text($"Total incl. ({invoice.CurrencyCode})");
                });

                static IContainer DataCell(IContainer c) =>
                    c.PaddingVertical(4).PaddingHorizontal(4).BorderBottom(1).BorderColor(Colors.Grey.Lighten3);

                var index = 1;
                foreach (var item in invoice.Items)
                {
                    table.Cell().Element(DataCell).Text(index++.ToString());
                    table.Cell().Element(DataCell).Text(item.Description);
                    table.Cell().Element(DataCell).AlignRight().Text(item.UnitPriceExclTax.ToString("F2"));
                    table.Cell().Element(DataCell).AlignRight().Text($"{item.TaxRate * 100:F1}%");
                    table.Cell().Element(DataCell).AlignRight().Text(item.TotalInclTax.ToString("F2"));
                }
            });

            col.Item().PaddingTop(12).AlignRight().Column(totals =>
            {
                totals.Item().PaddingHorizontal(4).Row(r =>
                {
                    r.RelativeItem().AlignRight().Text("Subtotal:");
                    r.ConstantItem(120).AlignRight().Text($"{invoice.Subtotal:F2} {invoice.CurrencyCode}");
                });
                totals.Item().PaddingHorizontal(4).Row(r =>
                {
                    r.RelativeItem().AlignRight().Text("Tax:");
                    r.ConstantItem(120).AlignRight().Text($"{invoice.VatAmount:F2} {invoice.CurrencyCode}");
                });
                totals.Item()
                    .BorderTop(1).BorderColor(Colors.Grey.Medium)
                    .PaddingTop(4).PaddingHorizontal(4)
                    .Row(r =>
                    {
                        r.RelativeItem().AlignRight().Text("TOTAL:").Bold();
                        r.ConstantItem(120).AlignRight().Text($"{invoice.Total:F2} {invoice.CurrencyCode}").Bold();
                    });
            });
        });
    }
}
