namespace Vetolib.Billing.Contracts;

public record InvoiceDto(
    Guid Id,
    string InvoiceNumber,
    Guid? PatientId,
    string? PatientName,
    string? OwnerName,
    string? OwnerPhone,
    Guid? AppointmentId,
    InvoiceStatus Status,
    IReadOnlyList<InvoiceItemDto> Items,
    decimal Subtotal,
    decimal VatRate,
    decimal VatAmount,
    decimal Total,
    string? Notes,
    DateTime CreatedAt,
    DateTime? PaidAt,
    DateTime? DueDate,
    Guid ClinicId,
    string? SellerSiren = null,
    string? SellerVatNumber = null,
    string? BuyerSiren = null,
    string? BuyerVatNumber = null,
    string BuyerName = "",
    string? BuyerAddress = null,
    OperationType? OperationType = null,
    string InvoiceTypeCode = "380",
    string? PaymentTerms = null,
    string CountryCode = "AE",
    string? PurchaseOrderReference = null);
