namespace Vetolib.AI.Contracts;

public enum HealthAlertType
{
    BreedSpecificScreening,
    AgeRelatedScreening,
    WeightTrend,
    VaccineGap,
    DentalProphylaxis,
    ChronicDiseaseFollowUp,
    SeniorWellness,
    MedicationReview,
    FalconMoltWeightLoss,
    FalconAspergillosisRisk,
    FalconBumblefoot,
    FalconTrichomoniasis,
    FalconMoltAnomaly,
    FalconHealthCertificate,
    FalconPostHuntRecovery,
    VaccinationDue,
    CamelTrypanosoma,
    CamelHeatStress,
    CamelFootRot,
    CamelMERSScreening,
    CamelRacingFitness,
    DogHeartwormScreening,
    DogObesityRisk,
    DogDentalDisease,
    DogParvovirusRisk,
    DogSeniorScreening,
    CatKidneyDiseaseScreening,
    CatHyperthyroidism,
    CatFelvRetest,
    CatDentalResorption,
    CatObesity
}
